name: Test Digital
favicon: null
layout_spectrum: 0.9177849791012704
typography_spectrum: 0.6182692579459399
title: 'So this is the grid beta, mmm interesting :-)'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2dcc4'
    - '#5e8298'
    - '#c4a99e'
    - '#1b6a8b'
    - '#124064'
  brandStrength: 0.6407486924435943
  lightness: 0.5436035797465593
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
